#!/bin/bash -e
CHECK_DIR=/tmp/cf_check_promises
CFENGINE_DIR=/var/cfengine
PRE_RECEIVE_EMAIL=/var/lib/gitolite/repositories/cfe3-files.git/hooks/post-receive-email

while read old new name
do
    if [ ! -d $CHECK_DIR ]
    then
        mkdir $CHECK_DIR
        git archive $new|tar -x -C $CHECK_DIR
    fi

    rm -rf $CFENGINE_DIR/masterfiles/*
    cp -r $CHECK_DIR/masterfiles/* $CFENGINE_DIR/masterfiles/
    rm -rf $CFENGINE_DIR/deployfiles/*
    cp -r $CHECK_DIR/deployfiles/* $CFENGINE_DIR/deployfiles/

    if [ -f $PRE_RECEIVE_EMAIL ]
    then
        echo $old $new $name | $PRE_RECEIVE_EMAIL
    fi
done
